export const options = [
    { label: "Adventure trip", value: "adventure trip" },
    { label: "Backpacking trip", value: "backpacking trip" },
    { label: "Beach trip", value: "beach trip" },
    { label: "Business trip", value: "business trip" },
    { label: "City break", value: "city break" },
    { label: "Couple", value: "couple" },
    { label: "Cruise trip", value: "cruise trip" },
    { label: "Cultural trip", value: "cultural trip" },
    { label: "Family trip", value: "family trip" },
    { label: "Food and wine trip", value: "food and wine trip" },
    { label: "Friendship trip", value: "friendship trip" },
    { label: "Gap year trip", value: "gap year trip" },
    { label: "Girls' trip", value: "girls trip" },
    { label: "Guys' trip", value: "guys trip" },
    { label: "Honeymoon", value: "honeymoon" },
    { label: "Leisure trip", value: "leisure trip" },
    { label: "Luxury trip", value: "luxury trip" },
    { label: "Mission trip", value: "mission trip" },
    { label: "Nature trip", value: "nature trip" },
    { label: "Pilgrimage", value: "pilgrimage" },
    { label: "Road trip", value: "road trip" },
    { label: "Romantic getaway", value: "romantic getaway" },
    { label: "Senior trip", value: "senior trip" },
    { label: "Solo trip", value: "solo trip" },
    { label: "Sports trip", value: "sports trip" },
    { label: "Student trip", value: "student trip" },
    { label: "Team-building trip", value: "team building trip" },
    { label: "Trekking trip", value: "trekking trip" },
    { label: "Vacation", value: "vacation" },
    { label: "Wellness trip", value: "wellness trip" },
    { label: "Wildlife trip", value: "wildlife trip" },
    { label: "Winter sports trip", value: "winter sports trip" },
    { label: "Youth trip", value: "youth trip" },
    { label: "Anniversary trip", value: "anniversary trip" },
    { label: "Bachelor/bachelorette party", value: "bachelor bachelorette party" },
    { label: "Birthday trip", value: "birthday trip" },
    { label: "Bucket list trip", value: "bucket list trip" },
    { label: "Camping trip", value: "camping trip" },
    { label: "Cycling trip", value: "cycling trip" },
    { label: "Diving trip", value: "diving trip" },
    { label: "Eco-tourism trip", value: "eco tourism trip" },
    { label: "Educational trip", value: "educational trip" },
    { label: "Exploration trip", value: "exploration trip" },
    { label: "Festival trip", value: "festival trip" },
    { label: "Fishing trip", value: "fishing trip" },
    { label: "Golf trip", value: "golf trip" },
    { label: "Hiking trip", value: "hiking trip" },
    { label: "History trip", value: "history trip" },
    { label: "Holiday trip", value: "holiday trip" },
    { label: "Incentive trip", value: "incentive trip" },
    { label: "Island trip", value: "island trip" },
    { label: "Ladies' trip", value: "ladies trip" },
    { label: "LGBTQ+ trip", value: "lgbtq trip" },
    { label: "Milestone trip", value: "milestone trip" },
    { label: "Motorcycle trip", value: "motorcycle trip" },
    { label: "Music trip", value: "music trip" },
    { label: "Outdoor adventure trip", value: "outdoor adventure trip" },
    { label: "Photography trip", value: "photography trip" },
    { label: "Relaxation trip", value: "relaxation trip" },
    { label: "Religious trip", value: "religious trip" },
    { label: "Retreat trip", value: "retreat trip" },
    { label: "Safari trip", value: "safari trip" },
    { label: "Scenic trip", value: "scenic trip" },
    { label: "Shopping trip", value: "shopping trip" },
    { label: "Skiing trip", value: "skiing trip" },
    { label: "Spa trip", value: "spa trip" },
    { label: "Spiritual trip", value: "spiritual trip" },
    { label: "Sports fan trip", value: "sports fan trip" },
    { label: "Summer camp trip", value: "summer camp trip" },
    { label: "Theme park trip", value: "theme park trip" },
    { label: "Tournament trip", value: "tournament trip" },
    { label: "Volunteer trip", value: "volunteer trip" },
    { label: "Wedding trip", value: "wedding trip" },
    { label: "Weekend getaway", value: "weekend getaway" },
    { label: "Wilderness trip", value: "wilderness trip" },
    { label: "Winter holiday trip", value: "winter holiday trip" },
    { label: "Workation trip", value: "workation trip" },
  ];
  